### ISSUE TITLE
Not activating the first lava switch before the Z-57 fight will softlock you

### ISSUE THREAD

**Issue by Hugoshido** [randovania/open-dread-rando#128] opened 2022-07-27 11:51 UTC
https://discordapp.com/channels/914291389293027329/914508458739511358/1001760638126800926

**Comment by duncathan** [comment] 2022-07-30 02:17
not a bug, strictly speaking

**Comment by Hugoshido** [comment] 2022-07-31 10:16
No it's not.. But maybe it's possible to get rid of the blast door in first place? Wouldn't change the routing at all and would help with this softlock

**Comment by duncathan** [comment] 2023-08-15 00:13
I think the way to do this is to add a new thermal door that blocks off the bomb launcher until the other door is opened. There's never a time where using the launcher without opening the door is useful, afaik

**Comment by MayberryZoom** [comment] 2024-03-04 14:32
This could use a similar approach to Golzuna where there's a warning message when you enter. It should probably be placed partially through the morph launcher?

**Comment by MayberryZoom** [comment] 2024-04-16 01:33
Fixed by #313

**Closed by MayberryZoom** 2024-04-16 01:33 UTC
Labels: enhancement
